/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankaotomasyonu;

/**
 *
 * @author YILMAZ
 */
public class AdminPanel extends javax.swing.JFrame {
    public static User currentUser ;
    public static int flag ; 
    public static int choose  ;
    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jArkaPanel = new javax.swing.JPanel();
        jCancelLabel = new javax.swing.JLabel();
        jGeriLabel = new javax.swing.JLabel();
        jVadeli = new javax.swing.JLabel();
        jAltin = new javax.swing.JLabel();
        jDolar = new javax.swing.JLabel();
        jEuro = new javax.swing.JLabel();
        jLimit = new javax.swing.JLabel();
        jKredi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPersonel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jArkaPanel.setBackground(new java.awt.Color(255, 255, 255));
        jArkaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCancelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        jCancelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCancelLabelMousePressed(evt);
            }
        });
        jArkaPanel.add(jCancelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 10, -1, -1));

        jGeriLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/leftArrow.png"))); // NOI18N
        jGeriLabel.setText("GERİ GİT");
        jGeriLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jGeriLabelMousePressed(evt);
            }
        });
        jArkaPanel.add(jGeriLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 443, -1, -1));

        jVadeli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jVadeli.setText("VADELİ HESAP ONAY");
        jVadeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jVadeliMousePressed(evt);
            }
        });
        jArkaPanel.add(jVadeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jAltin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jAltin.setText("ALTIN HESAP ONAY");
        jAltin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jAltinMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jAltinMousePressed(evt);
            }
        });
        jArkaPanel.add(jAltin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        jDolar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jDolar.setText("DOLAR HESAP ONAY");
        jDolar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jDolarMousePressed(evt);
            }
        });
        jArkaPanel.add(jDolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 110, -1, -1));

        jEuro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jEuro.setText("EURO HESAP ONAY");
        jEuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jEuroMousePressed(evt);
            }
        });
        jArkaPanel.add(jEuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 110, -1, -1));

        jLimit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLimit.setText("LİMİT ISTEK");
        jLimit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLimitMousePressed(evt);
            }
        });
        jArkaPanel.add(jLimit, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 110, -1, -1));

        jKredi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jKredi.setText("KREDİ ISTEK");
        jKredi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jKrediMousePressed(evt);
            }
        });
        jArkaPanel.add(jKredi, new org.netbeans.lib.awtextra.AbsoluteConstraints(856, 110, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TC", "NO", "ESKİ LİMİT", "YENİ LİMİT", "MESAJ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 92, Short.MAX_VALUE))
        );

        jArkaPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 174, 460, 240));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TC", "HESAPNO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 77, Short.MAX_VALUE))
        );

        jArkaPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 174, 570, 220));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TC", "KREDİ", "BORC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.getTableHeader().setReorderingAllowed(false);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable3MousePressed(evt);
            }
        });
        jPanel3.setVisible(false);
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
            jTable3.getColumnModel().getColumn(1).setResizable(false);
            jTable3.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        jArkaPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 170, 330, 160));

        jPersonel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPersonel.setText("PERSONELLER");
        if(flag==1) jPersonel.setVisible(false);
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPersonel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPersonelMousePressed(evt);
            }
        });
        jArkaPanel.add(jPersonel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jArkaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jArkaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCancelLabelMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        System.exit(1);
    }//GEN-LAST:event_jCancelLabelMousePressed

    private void jGeriLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGeriLabelMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        AdminLogin.mainAdminLogin(flag);
    }//GEN-LAST:event_jGeriLabelMousePressed

    private void jAltinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAltinMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jAltinMouseEntered

    private void jAltinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAltinMousePressed
        // TODO add your handling code here:

        choose = 2 ; 
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
        jPanel3.setVisible(false);        
       javax.swing.table.DefaultTableModel table1 = (javax.swing.table.DefaultTableModel)jTable1.getModel();
       table1.setRowCount(0);
       java.util.ArrayList<String[]> rObj = ((Personel)currentUser).hesapIstek(2);
       if(rObj == null) return ;
        for(int i  = 0 ; i < rObj.size();++i){
            table1.addRow(rObj.get(i));
        }       
       
    }//GEN-LAST:event_jAltinMousePressed

    private void jVadeliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVadeliMousePressed
        // TODO add your handling code here:
        choose = 1  ;
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);  
        jPanel3.setVisible(false);
        javax.swing.table.DefaultTableModel table1 = (javax.swing.table.DefaultTableModel)jTable1.getModel();
        table1.setRowCount(0);
        java.util.ArrayList<String[]>rObj = ((Personel)currentUser).hesapIstek(1);
               if(rObj == null) return ;

        for(int i  = 0 ; i < rObj.size();++i){
            table1.addRow(rObj.get(i));
        }
     
    }//GEN-LAST:event_jVadeliMousePressed

    private void jDolarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDolarMousePressed
        // TODO add your handling code here:
        choose = 3  ;
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
        jPanel3.setVisible(false);        
        javax.swing.table.DefaultTableModel table1 = (javax.swing.table.DefaultTableModel)jTable1.getModel();
        table1.setRowCount(0);
        java.util.ArrayList<String[]>rObj = ((Personel)currentUser).hesapIstek(3);
               if(rObj == null) return ;

        for(int i  = 0 ; i < rObj.size();++i){
            table1.addRow(rObj.get(i));
        }        
    }//GEN-LAST:event_jDolarMousePressed

    private void jEuroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEuroMousePressed
        // TODO add your handling code here:
        choose = 4 ; 
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
        jPanel3.setVisible(false);        
         javax.swing.table.DefaultTableModel table1 = (javax.swing.table.DefaultTableModel)jTable1.getModel();
        table1.setRowCount(0);
        java.util.ArrayList<String[]>rObj = ((Personel)currentUser).hesapIstek(4);
               if(rObj == null) return ;

        for(int i  = 0 ; i < rObj.size();++i){
            table1.addRow(rObj.get(i));
        }       
    }//GEN-LAST:event_jEuroMousePressed

    private void jLimitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLimitMousePressed
        // TODO add your handling code here:
        choose = 5 ; 
        jPanel2.setVisible(true);
        jPanel1.setVisible(false);
        jPanel3.setVisible(false);
         javax.swing.table.DefaultTableModel table2 = (javax.swing.table.DefaultTableModel)jTable2.getModel();
         table2.setRowCount(0);
         java.util.ArrayList<String[]> rObj = ((Personel)currentUser).digerIstek(5);
               if(rObj == null) return ;

        for(int i  = 0 ; i < rObj.size();++i){
            table2.addRow(rObj.get(i));
        }          
        
    }//GEN-LAST:event_jLimitMousePressed

    private void jKrediMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jKrediMousePressed
        // TODO add your handling code here:
        choose = 6 ; 
        jPanel2.setVisible(false);
        jPanel1.setVisible(false); 
        jPanel3.setVisible(true);   
         javax.swing.table.DefaultTableModel table3 = (javax.swing.table.DefaultTableModel)jTable3.getModel();
        table3.setRowCount(0);
        java.util.ArrayList<String[]> rObj = ((Personel)currentUser).digerIstek(6);
               if(rObj == null) return ;

        for(int i  = 0 ; i < rObj.size();++i){
            table3.addRow(rObj.get(i));
        }         
    }//GEN-LAST:event_jKrediMousePressed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
         int index = jTable1.getSelectedRow();
        if(index!=-1){
           String tc = jTable1.getValueAt(index,0).toString();
           String hesapNo = jTable1.getValueAt(index,1).toString();
           jPanel1.setVisible(false);
           AdminHesap.mainAdminHesap(currentUser, tc, hesapNo,choose);
        }
    }//GEN-LAST:event_jTable1MousePressed

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        // TODO add your handling code here:
        int index = jTable2.getSelectedRow();
        if(index!=-1){
           String tc = jTable2.getValueAt(index,0).toString();
           String kartNo = jTable2.getValueAt(index,1).toString();
           String eskiLimit = jTable2.getValueAt(index, 2).toString();
           String yeniLimit = jTable2.getValueAt(index, 3).toString();
           String mesaj = jTable2.getValueAt(index, 4).toString();
           AdminLimit.mainAdminLimit(currentUser, tc, kartNo, eskiLimit, yeniLimit, mesaj);
           jPanel2.setVisible(false);

        }       
    }//GEN-LAST:event_jTable2MousePressed

    private void jTable3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MousePressed
        // TODO add your handling code here:
        int index = jTable3.getSelectedRow();
        if(index!=-1){
           String tc = jTable3.getValueAt(index,0).toString();
           String para = jTable3.getValueAt(index,1).toString();
           String borc = jTable3.getValueAt(index, 2).toString();

           AdminBorc.mainAdminBorc(currentUser, tc, Integer.valueOf(para),Double.valueOf(borc));
           jPanel3.setVisible(false);

        }          
    }//GEN-LAST:event_jTable3MousePressed

    private void jPersonelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPersonelMousePressed
        // TODO add your handling code here:
        jTable1.setVisible(false);
        jTable2.setVisible(false);
        jTable3.setVisible(false);
        AdminPersonel.mainAdminPersonel(currentUser);
    }//GEN-LAST:event_jPersonelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void mainAdminPanel(User currentUser, int flag) {
        AdminPanel.currentUser = currentUser;
        AdminPanel.flag = flag ; 
        choose = 0 ; 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAltin;
    private javax.swing.JPanel jArkaPanel;
    private javax.swing.JLabel jCancelLabel;
    private javax.swing.JLabel jDolar;
    private javax.swing.JLabel jEuro;
    private javax.swing.JLabel jGeriLabel;
    private javax.swing.JLabel jKredi;
    private javax.swing.JLabel jLimit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jPersonel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel jVadeli;
    // End of variables declaration//GEN-END:variables
}
