/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankaotomasyonu;

/**
 *
 * @author YILMAZ
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jArkaPanel = new javax.swing.JPanel();
        jSolPanel = new javax.swing.JPanel();
        jResimLabel = new javax.swing.JLabel();
        jMusteriText = new javax.swing.JLabel();
        jSagPanel = new javax.swing.JPanel();
        jAdminResimLabel = new javax.swing.JLabel();
        jAdminText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jArkaPanel.setBackground(new java.awt.Color(255, 255, 255));

        jSolPanel.setBackground(new java.awt.Color(255, 255, 255));

        jResimLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/card.png"))); // NOI18N
        jResimLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jResimLabelMousePressed(evt);
            }
        });

        jMusteriText.setFont(new java.awt.Font("Sitka Subheading", 0, 36)); // NOI18N
        jMusteriText.setText("MÜŞTERİ GİRİŞİ");
        jMusteriText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMusteriTextMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jSolPanelLayout = new javax.swing.GroupLayout(jSolPanel);
        jSolPanel.setLayout(jSolPanelLayout);
        jSolPanelLayout.setHorizontalGroup(
            jSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSolPanelLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(jSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jSolPanelLayout.createSequentialGroup()
                        .addComponent(jMusteriText)
                        .addContainerGap(256, Short.MAX_VALUE))
                    .addGroup(jSolPanelLayout.createSequentialGroup()
                        .addComponent(jResimLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jSolPanelLayout.setVerticalGroup(
            jSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSolPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jResimLabel)
                .addGap(18, 18, 18)
                .addComponent(jMusteriText)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jSagPanel.setBackground(new java.awt.Color(255, 255, 255));

        jAdminResimLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin.png"))); // NOI18N
        jAdminResimLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jAdminResimLabelMousePressed(evt);
            }
        });

        jAdminText.setFont(new java.awt.Font("Sitka Subheading", 0, 36)); // NOI18N
        jAdminText.setText("ADMİN GİRİŞİ");
        jAdminText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jAdminTextMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jSagPanelLayout = new javax.swing.GroupLayout(jSagPanel);
        jSagPanel.setLayout(jSagPanelLayout);
        jSagPanelLayout.setHorizontalGroup(
            jSagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSagPanelLayout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addGroup(jSagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSagPanelLayout.createSequentialGroup()
                        .addComponent(jAdminText)
                        .addGap(204, 204, 204))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSagPanelLayout.createSequentialGroup()
                        .addComponent(jAdminResimLabel)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSagPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        jSagPanelLayout.setVerticalGroup(
            jSagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSagPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(jAdminResimLabel)
                .addGap(28, 28, 28)
                .addComponent(jAdminText)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jArkaPanelLayout = new javax.swing.GroupLayout(jArkaPanel);
        jArkaPanel.setLayout(jArkaPanelLayout);
        jArkaPanelLayout.setHorizontalGroup(
            jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jArkaPanelLayout.createSequentialGroup()
                .addComponent(jSolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSagPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jArkaPanelLayout.setVerticalGroup(
            jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSagPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jArkaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jArkaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jResimLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jResimLabelMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        MusteriLogin.mainMusteriLogin();
    }//GEN-LAST:event_jResimLabelMousePressed

    private void jAdminResimLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAdminResimLabelMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        PersonelOrYönetici.mainPersonelOrYönetici();
     
    }//GEN-LAST:event_jAdminResimLabelMousePressed

    private void jMusteriTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMusteriTextMousePressed
        // TODO add your handling code here:
     this.setVisible(false);
     this.dispose();
     MusteriLogin.mainMusteriLogin();
    }//GEN-LAST:event_jMusteriTextMousePressed

    private void jAdminTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAdminTextMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jAdminTextMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        System.exit(1);
    }//GEN-LAST:event_jLabel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void mainLogin() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAdminResimLabel;
    private javax.swing.JLabel jAdminText;
    private javax.swing.JPanel jArkaPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jMusteriText;
    private javax.swing.JLabel jResimLabel;
    private javax.swing.JPanel jSagPanel;
    private javax.swing.JPanel jSolPanel;
    // End of variables declaration//GEN-END:variables
}
