/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankaotomasyonu;

/**
 *
 * @author YILMAZ
 */
public class MusteriMain extends javax.swing.JFrame {
    public static User currentUser = null ; 
    /**
     * Creates new form MusteriMain
     */
    public MusteriMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jArkaPlanLabel = new javax.swing.JPanel();
        jGeriLabel = new javax.swing.JLabel();
        jPpLabel = new javax.swing.JLabel();
        jExitLabel = new javax.swing.JLabel();
        jAdLabel = new javax.swing.JLabel();
        jMenuLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jArkaPlanLabel.setBackground(new java.awt.Color(255, 255, 255));

        jGeriLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/quit.png"))); // NOI18N
        jGeriLabel.setText("GÜVENLİ CIKIS");
        jGeriLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jGeriLabelMousePressed(evt);
            }
        });

        jPpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/woman.png"))); // NOI18N
        if(MusteriMain.currentUser.getCinsiyet().equals("ERKEK")){
            jPpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/man.png")));
        }

        jExitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        jExitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jExitLabelMousePressed(evt);
            }
        });

        jAdLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jAdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAdLabel.setText("ADMİN ADMİN");
        jAdLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        String ad = MusteriMain.currentUser.getAd();
        String soyad = MusteriMain.currentUser.getSoyad();
        jAdLabel.setText(ad+" "+soyad);

        jMenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        jMenuLabel.setText("MENU  ");
        jMenuLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jMenuLabel.setFocusable(false);
        jMenuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuLabelMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/uyari.png"))); // NOI18N
        jLabel2.setText("CEO'MUZ YILMAZ ALPEREN'IN DUYURUSU");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("BORSA FİYATLARIMIZ HER PROGRAM\nACILDIGINDA DEGİSMEKTEDİR!!!\nBU DEGISMEYE BAGLI OLARAK \nHER PROGRAM ACILDIGINDA \nYATIRIMLARINIZ DEGER KAZANIR ;)");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jArkaPlanLabelLayout = new javax.swing.GroupLayout(jArkaPlanLabel);
        jArkaPlanLabel.setLayout(jArkaPlanLabelLayout);
        jArkaPlanLabelLayout.setHorizontalGroup(
            jArkaPlanLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jArkaPlanLabelLayout.createSequentialGroup()
                .addGroup(jArkaPlanLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jArkaPlanLabelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jGeriLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jMenuLabel))
                    .addGroup(jArkaPlanLabelLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jPpLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jExitLabel))
                    .addGroup(jArkaPlanLabelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(jArkaPlanLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jArkaPlanLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)))
                        .addGap(0, 122, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jArkaPlanLabelLayout.setVerticalGroup(
            jArkaPlanLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jArkaPlanLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jArkaPlanLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPpLabel)
                    .addComponent(jExitLabel))
                .addGap(18, 18, 18)
                .addComponent(jAdLabel)
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jArkaPlanLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jGeriLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jMenuLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jArkaPlanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jArkaPlanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jExitLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitLabelMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        System.exit(1);
    }//GEN-LAST:event_jExitLabelMousePressed

    private void jGeriLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGeriLabelMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        MusteriLogin.mainMusteriLogin();
    }//GEN-LAST:event_jGeriLabelMousePressed

    private void jMenuLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLabelMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        MusteriMenu.mainMusteriMenu(currentUser);
    }//GEN-LAST:event_jMenuLabelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void mainMusteriMain(User currentUser) {
        MusteriMain.currentUser = currentUser ; 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAdLabel;
    private javax.swing.JPanel jArkaPlanLabel;
    private javax.swing.JLabel jExitLabel;
    private javax.swing.JLabel jGeriLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jMenuLabel;
    private javax.swing.JLabel jPpLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
