/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankaotomasyonu;

/**
 *
 * @author YILMAZ
 */
public class ParaTransferRakip2 extends javax.swing.JFrame {
    public static User currentUser ; 
    public static String vadesizHesapNo;
    public static String vadesizBakiye;
    /**
     * Creates new form ParaTransferRakip2
     */
    public ParaTransferRakip2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jArkaPanel = new javax.swing.JPanel();
        jCancelLabel = new javax.swing.JLabel();
        jGeriLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jOndalikText = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jTamText = new javax.swing.JTextField();
        jNoktaLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jArkaPanel.setBackground(new java.awt.Color(255, 255, 255));

        jCancelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        jCancelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCancelLabelMousePressed(evt);
            }
        });

        jGeriLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/leftArrow.png"))); // NOI18N
        jGeriLabel.setText("GERİ GİT");
        jGeriLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jGeriLabelMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("NE KADAR GÖNDERMEK İSTİYORSUNUZ ?");

        jOndalikText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jOndalikText.setBorder(null);
        jOndalikText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jOndalikTextKeyReleased(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jTamText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTamText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTamText.setBorder(null);
        jTamText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTamTextKeyReleased(evt);
            }
        });

        jNoktaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jNoktaLabel.setText(".");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/right.png"))); // NOI18N
        jLabel3.setText("DEVAM ET");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jArkaPanelLayout = new javax.swing.GroupLayout(jArkaPanel);
        jArkaPanel.setLayout(jArkaPanelLayout);
        jArkaPanelLayout.setHorizontalGroup(
            jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jArkaPanelLayout.createSequentialGroup()
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jArkaPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCancelLabel))
                    .addGroup(jArkaPanelLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel2)
                        .addGap(0, 127, Short.MAX_VALUE))
                    .addGroup(jArkaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jGeriLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
            .addGroup(jArkaPanelLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jTamText, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jNoktaLabel)
                .addGap(18, 18, 18)
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addComponent(jOndalikText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jArkaPanelLayout.setVerticalGroup(
            jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jArkaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCancelLabel)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(66, 66, 66)
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTamText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNoktaLabel)
                    .addComponent(jOndalikText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGeriLabel)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jArkaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jArkaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCancelLabelMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        System.exit(1);
    }//GEN-LAST:event_jCancelLabelMousePressed

    private void jGeriLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGeriLabelMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        ParaTransferRakip1.mainParaTransferRakip1(currentUser);
    }//GEN-LAST:event_jGeriLabelMousePressed

    private void jOndalikTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jOndalikTextKeyReleased
        // TODO add your handling code here:
        long tam, ondalik;
        double kullaniciSayisi;
        double vadesizSayi;
        try{
            if(jTamText.getText().equals(""));
            else  Long.valueOf(jTamText.getText());

            if(jOndalikText.getText().equals("")) ;
            else  Long.valueOf(jOndalikText.getText());
            // SİMDİYE KADAR NUMBER FORMATINDA SIKINTI VARSA DİYE YAPTIK EGER BURAYI GECER ISE SAYI FORMATINDA SIKINTI YOKTUR!
            if(jTamText.getText().equals("")&&jOndalikText.getText().equals("")){
                kullaniciSayisi = 0.0 ;
            }
            else if(jTamText.getText().equals("")||jOndalikText.getText().equals("")){
                if(jTamText.getText().equals("")){
                    kullaniciSayisi = Double.valueOf("0."+jOndalikText.getText());
                }
                else{
                    kullaniciSayisi = Double.valueOf(jTamText.getText()+".0");
                }
            }
            else{
                kullaniciSayisi = Double.valueOf(jTamText.getText()+"."+jOndalikText.getText());
            }
            vadesizSayi = Double.valueOf(vadesizBakiye);
            if(vadesizSayi < kullaniciSayisi){
                java.util.StringTokenizer token = new java.util.StringTokenizer(vadesizBakiye,".");
                jTamText.setText(token.nextToken());
                jOndalikText.setText(token.nextToken());
            }
            else{

            }

        }catch(NumberFormatException e){
            jOndalikText.setText("");
        }catch(NullPointerException e1){
            javax.swing.JOptionPane.showMessageDialog(null,"BİLGİNİN SAKNLAMASINDA HATA VAR!");
        }
    }//GEN-LAST:event_jOndalikTextKeyReleased

    private void jTamTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTamTextKeyReleased
        // TODO add your handling code here:
        long tam,ondalik;
        double kullaniciSayisi ; // Kullanıcın istedgi tutar ama vadesiz hesabından daha fazla girmis ise bunu kontol etmem lazım!
        double vadesizSayi ;
        try{
            if(jTamText.getText().equals(""));
            else  Long.valueOf(jTamText.getText());

            if(jOndalikText.getText().equals("")) ;
            else  Long.valueOf(jOndalikText.getText());
            // SİMDİYE KADAR NUMBER FORMATINDA SIKINTI VARSA DİYE YAPTIK EGER BURAYI GECER ISE SAYI FORMATINDA SIKINTI YOKTUR!
            if(jTamText.getText().equals("")) tam = 0 ;
            else tam = Long.valueOf(jTamText.getText());
            vadesizSayi = Double.valueOf(vadesizBakiye);
            if((long)vadesizSayi < tam){
                jTamText.setText(String.valueOf((long)vadesizSayi));
            }
            else{

            }

        }catch(NumberFormatException e ){
            jTamText.setText("");
        }

    }//GEN-LAST:event_jTamTextKeyReleased

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        String tam = jTamText.getText();
        String ondalik = jOndalikText.getText();
        if(tam == null || tam.equals("")){
            tam = "0";
        }
        if(ondalik == null || ondalik.equals("")){
            ondalik ="0";
        }
        String para = tam+"."+ondalik;

        try{
            double vadeliHesapPara = Double.valueOf(para);
            if(vadeliHesapPara <=0){
                javax.swing.JOptionPane.showMessageDialog(null,"YUKLEMEK ISTEDIGINIZ BAKİYE NEGATİF VEYA SIFIR OLAMAZ");
                this.setVisible(false);
                this.dispose();
                ParaTransferRakip1.mainParaTransferRakip1(currentUser);
                return ;
            }
            else{
                if(!((((Musteri)currentUser).vadesizHesapBakiye(vadesizHesapNo, vadeliHesapPara, false)))){
                    // yani cikarma islemi bakiye yetersizliginden olmamis ise
                    this.setVisible(false);
                    this.dispose();
                    VadesizFrame.mainVadesizFrame(currentUser);
                    javax.swing.JOptionPane.showMessageDialog(null,"SECİLEN VADESİZ HESAPTA BU KADAR PARA YOK!");
                }
                else{
                    this.setVisible(false);
                    this.dispose();
                    // 3. asama
                    ParaTransferRakip3.mainParaTransferRakip3(currentUser, vadesizHesapNo, vadesizBakiye, vadeliHesapPara);
                }
            }

        }catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null,"LUTFEN SADECE RAKAM GİRİNİZ!");
        }
    }//GEN-LAST:event_jLabel3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void mainParaTransferRakip2(User currentUser,String vadesizHesapNo,String vadesizBakiye) {
        ParaTransferRakip2.currentUser = currentUser ;
        ParaTransferRakip2.vadesizHesapNo = vadesizHesapNo;
        ParaTransferRakip2.vadesizBakiye = vadesizBakiye;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParaTransferRakip2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParaTransferRakip2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParaTransferRakip2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParaTransferRakip2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParaTransferRakip2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jArkaPanel;
    private javax.swing.JLabel jCancelLabel;
    private javax.swing.JLabel jGeriLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jNoktaLabel;
    private javax.swing.JTextField jOndalikText;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTamText;
    // End of variables declaration//GEN-END:variables
}
