/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankaotomasyonu;

/**
 *
 * @author YILMAZ
 */
public class ProfilOnayKod extends javax.swing.JFrame {
        public static User currentUser = null ; 
        public static int onayKodu ; 
        public static String yeniSifre = null ; 
    /**
     * Creates new form ProfilOnayKod
     */
    public ProfilOnayKod() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jArkaPanel = new javax.swing.JPanel();
        jLockLabel = new javax.swing.JLabel();
        jCancelLabel = new javax.swing.JLabel();
        jOnayLabel = new javax.swing.JLabel();
        jOnayText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jArkaPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLockLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lock1.png"))); // NOI18N

        jCancelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        jCancelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCancelLabelMousePressed(evt);
            }
        });

        jOnayLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jOnayLabel.setText("ONAY KODU GİR");

        jOnayText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jOnayText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jOnayText.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ONAY KODU GİR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jArkaPanelLayout = new javax.swing.GroupLayout(jArkaPanel);
        jArkaPanel.setLayout(jArkaPanelLayout);
        jArkaPanelLayout.setHorizontalGroup(
            jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jArkaPanelLayout.createSequentialGroup()
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jArkaPanelLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLockLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCancelLabel))
                    .addGroup(jArkaPanelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jOnayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jOnayText)
                                .addComponent(jSeparator1)))
                        .addGap(0, 156, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jArkaPanelLayout.setVerticalGroup(
            jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jArkaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCancelLabel)
                .addGap(1, 1, 1)
                .addComponent(jLockLabel)
                .addGap(55, 55, 55)
                .addComponent(jOnayLabel)
                .addGap(18, 18, 18)
                .addComponent(jOnayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jArkaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jArkaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCancelLabelMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        System.exit(1);
    }//GEN-LAST:event_jCancelLabelMousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        if(jOnayText.getText().equals(String.valueOf(ProfilOnayKod.onayKodu))){
            java.io.File tempFile  = null ; 
            String tutucu = null ; 
            String specifier = null ; 
            java.io.BufferedReader readFromFile = null ; 
            java.io.BufferedWriter writeToFile = null ; 
            String keeper = null ; 
            java.util.StringTokenizer token = null ; 
            try{
                tempFile = new java.io.File("src/Files/tempUser.txt");
                if(tempFile.createNewFile()); // tempUser olustu!!
                writeToFile  = new java.io.BufferedWriter(new java.io.FileWriter(tempFile));
                readFromFile = new java.io.BufferedReader(new java.io.FileReader("src/Files/user.txt"));
                while((keeper=readFromFile.readLine())!=null){
                    token = new java.util.StringTokenizer(keeper,"//");
                    specifier = token.nextToken();
                    tutucu = token.nextToken();
                    if(tutucu.equals(ProfilOnayKod.currentUser.getTc())){
                        writeToFile.write(specifier+"//"+currentUser.getTc()+"//"+
                                ProfilOnayKod.yeniSifre+"//"+currentUser.getAd()+"//"+
                                currentUser.getSoyad()+"//"+currentUser.getCinsiyet()+"//"
                        +currentUser.getDate().day+"."+currentUser.getDate().month+"."+currentUser.getDate().year+"//"
                        +currentUser.getTelNo());
                        writeToFile.newLine();
                    }
                    else{
                        writeToFile.write(keeper);
                        writeToFile.newLine();
                    }
                }
                readFromFile.close();
                writeToFile.close();
                //-------------------------------------------------------------------------------------------------------
                tempFile = new java.io.File("src/Files/tempUser.txt");
                readFromFile = new java.io.BufferedReader(new java.io.FileReader(tempFile));
                writeToFile = new java.io.BufferedWriter(new java.io.FileWriter("src/Files/user.txt"));
                while((keeper=readFromFile.readLine())!=null){
                    writeToFile.write(keeper);
                    writeToFile.newLine();
                }
                writeToFile.close();
                readFromFile.close();
                tempFile.delete();
                this.setVisible(false);
                this.dispose();
                MusteriLogin.mainMusteriLogin();
                
            }catch(java.io.IOException e ){
                javax.swing.JOptionPane.showMessageDialog(null,"DOSYA YOLU BULUNAMADI\nIDE ILE DENER MISIN ? ");
            }
            catch(NullPointerException e1){
                e1.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(null,"VERİNİN SAKLANMASI İLE İLGİLİ HATA VAR!");
            }
            catch(Exception e2){
                javax.swing.JOptionPane.showMessageDialog(null,"BİR SEY OLDU!");
            }
            
            
            
            
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(null,"ONAY KODU YANLIS");
        }
    }//GEN-LAST:event_jButton1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void mainProFilOnayKod(int onayKodu,User currentUser, String yeniSifre) {
        ProfilOnayKod.onayKodu = onayKodu;
        ProfilOnayKod.yeniSifre = yeniSifre;
        ProfilOnayKod.currentUser = currentUser;
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfilOnayKod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfilOnayKod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfilOnayKod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfilOnayKod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfilOnayKod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jArkaPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jCancelLabel;
    private javax.swing.JLabel jLockLabel;
    private javax.swing.JLabel jOnayLabel;
    private javax.swing.JTextField jOnayText;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
