/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankaotomasyonu;

/**
 *
 * @author YILMAZ
 */
public class VadeliIcınBakiye extends javax.swing.JFrame {
    public static User currentUser = null ; 
    public static String vadeliHesapNo = null ;
    public static VadesizHesap vadesizHesap = null ; 
    /**
     * Creates new form VadeliIcınBakiye
     */
    public VadeliIcınBakiye() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jArkaPanel = new javax.swing.JPanel();
        jCancelLabel = new javax.swing.JLabel();
        jGeriLabel = new javax.swing.JLabel();
        jBakiyeLabel = new javax.swing.JLabel();
        jTamText = new javax.swing.JTextField();
        jNoktaLabel = new javax.swing.JLabel();
        jOndalikText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTlLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jArkaPanel.setBackground(new java.awt.Color(255, 255, 255));

        jCancelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        jCancelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCancelLabelMousePressed(evt);
            }
        });

        jGeriLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/leftArrow.png"))); // NOI18N
        jGeriLabel.setText("GERİ GİT");
        jGeriLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jGeriLabelMousePressed(evt);
            }
        });

        jBakiyeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBakiyeLabel.setText("BAKİYE GİRİNİZ");

        jTamText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTamText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTamText.setBorder(null);
        jTamText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTamTextKeyReleased(evt);
            }
        });

        jNoktaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jNoktaLabel.setText(".");

        jOndalikText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jOndalikText.setBorder(null);
        jOndalikText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jOndalikTextKeyReleased(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/right.png"))); // NOI18N
        jLabel1.setText("DEVAM ET");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jTlLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tl.png"))); // NOI18N

        javax.swing.GroupLayout jArkaPanelLayout = new javax.swing.GroupLayout(jArkaPanel);
        jArkaPanel.setLayout(jArkaPanelLayout);
        jArkaPanelLayout.setHorizontalGroup(
            jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jArkaPanelLayout.createSequentialGroup()
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jArkaPanelLayout.createSequentialGroup()
                        .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jArkaPanelLayout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(jBakiyeLabel))
                            .addGroup(jArkaPanelLayout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator1)
                                    .addComponent(jTamText, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jNoktaLabel)
                                .addGap(18, 18, 18)
                                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator2)
                                    .addComponent(jOndalikText, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addComponent(jTlLabel)))
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jArkaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jArkaPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jCancelLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jArkaPanelLayout.createSequentialGroup()
                                .addComponent(jGeriLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))))
                .addContainerGap())
        );
        jArkaPanelLayout.setVerticalGroup(
            jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jArkaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCancelLabel)
                .addGap(25, 25, 25)
                .addComponent(jBakiyeLabel)
                .addGap(76, 76, 76)
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTlLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTamText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jNoktaLabel)
                        .addComponent(jOndalikText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGeriLabel)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jArkaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jArkaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCancelLabelMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        System.exit(1);
    }//GEN-LAST:event_jCancelLabelMousePressed

    private void jGeriLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGeriLabelMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        VadeliIcınVadesizHesap.mainVadeliIcınVadesizFrame(currentUser, vadeliHesapNo);
    }//GEN-LAST:event_jGeriLabelMousePressed

    private void jTamTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTamTextKeyReleased
        // TODO add your handling code here:
        long tam,ondalik;
        double kullaniciSayisi ; // Kullanıcın istedgi tutar ama vadesiz hesabından daha fazla girmis ise bunu kontol etmem lazım!
        double vadesizSayi ; 
        try{
            if(jTamText.getText().equals("")); 
            else  Long.valueOf(jTamText.getText());
            
            if(jOndalikText.getText().equals("")) ; 
            else  Long.valueOf(jOndalikText.getText());
            // SİMDİYE KADAR NUMBER FORMATINDA SIKINTI VARSA DİYE YAPTIK EGER BURAYI GECER ISE SAYI FORMATINDA SIKINTI YOKTUR!
            if(jTamText.getText().equals("")) tam = 0 ; 
            else tam = Long.valueOf(jTamText.getText());
            vadesizSayi = Double.valueOf(vadesizHesap.getBakiye());
            if((long)vadesizSayi < tam){
                jTamText.setText(String.valueOf((long)vadesizSayi));
            }
            else{
                
            }
            
        }catch(NumberFormatException e ){
            jTamText.setText("");
        }
        
         
    }//GEN-LAST:event_jTamTextKeyReleased

    private void jOndalikTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jOndalikTextKeyReleased
        // TODO add your handling code here:
        long tam, ondalik;
        double kullaniciSayisi;
        double vadesizSayi;
        try{
            if(jTamText.getText().equals("")); 
            else  Long.valueOf(jTamText.getText());
            
            if(jOndalikText.getText().equals("")) ; 
            else  Long.valueOf(jOndalikText.getText());
            // SİMDİYE KADAR NUMBER FORMATINDA SIKINTI VARSA DİYE YAPTIK EGER BURAYI GECER ISE SAYI FORMATINDA SIKINTI YOKTUR! 
            if(jTamText.getText().equals("")&&jOndalikText.getText().equals("")){
                kullaniciSayisi = 0.0 ; 
            }
            else if(jTamText.getText().equals("")||jOndalikText.getText().equals("")){
                if(jTamText.getText().equals("")){
                    kullaniciSayisi = Double.valueOf("0."+jOndalikText.getText());
                }
                else{
                    kullaniciSayisi = Double.valueOf(jTamText.getText()+".0");
                }
            }
            else{
                kullaniciSayisi = Double.valueOf(jTamText.getText()+"."+jOndalikText.getText());
            }
            vadesizSayi = Double.valueOf(vadesizHesap.getBakiye());
            if(vadesizSayi < kullaniciSayisi){
                java.util.StringTokenizer token = new java.util.StringTokenizer(vadesizHesap.getBakiye(),".");
                jTamText.setText(token.nextToken());
                jOndalikText.setText(token.nextToken());
            }
            else{
                
            }
            
        }catch(NumberFormatException e){
            jOndalikText.setText("");
        }catch(NullPointerException e1){
            javax.swing.JOptionPane.showMessageDialog(null,"BİLGİNİN SAKNLAMASINDA HATA VAR!");
        }
    }//GEN-LAST:event_jOndalikTextKeyReleased

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        String tam = jTamText.getText();
        String ondalik = jOndalikText.getText();
        if(tam == null || tam.equals("")){
            tam = "0";
        }
        if(ondalik == null || ondalik.equals("")){
            ondalik ="0";
        }
        String para = tam+"."+ondalik;
        
        try{
        double vadeliHesapPara = Double.valueOf(para);
        if(vadeliHesapPara <=0){
            javax.swing.JOptionPane.showMessageDialog(null,"YUKLEMEK ISTEDIGINIZ BAKİYE NEGATİF VEYA SIFIR OLAMAZ");
            this.setVisible(false);
            this.dispose();
            VadeliIcınVadesizHesap.mainVadeliIcınVadesizFrame(currentUser, vadeliHesapNo);
            return ; 
        }
        else{
            if(!((((Musteri)currentUser).vadesizHesapBakiye(vadesizHesap.getHesapNo(), vadeliHesapPara, false)))){
                // yani cikarma islemi bakiye yetersizliginden olmamis ise
                this.setVisible(false);
                this.dispose();
                VadeliFrame.mainVadeliFrame(currentUser);
                javax.swing.JOptionPane.showMessageDialog(null,"SECİLEN VADESİZ HESAPTA BU KADAR PARA YOK!");
            }
            else{
                this.setVisible(false);
                this.dispose();
                VadeliGünFrame.mainVadeliGünFrame(currentUser, vadesizHesap, vadeliHesapPara, vadeliHesapNo);
            }
        }
        
        }catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null,"LUTFEN SADECE RAKAM GİRİNİZ!");
        }
    }//GEN-LAST:event_jLabel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void mainVadeliIcınBakiye(User currentUser,String vadeliHesapNo,VadesizHesap vadesizHesap) {
        VadeliIcınBakiye.currentUser = currentUser;
        VadeliIcınBakiye.vadeliHesapNo = vadeliHesapNo;
        VadeliIcınBakiye.vadesizHesap = vadesizHesap;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VadeliIcınBakiye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VadeliIcınBakiye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VadeliIcınBakiye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VadeliIcınBakiye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VadeliIcınBakiye().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jArkaPanel;
    private javax.swing.JLabel jBakiyeLabel;
    private javax.swing.JLabel jCancelLabel;
    private javax.swing.JLabel jGeriLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNoktaLabel;
    private javax.swing.JTextField jOndalikText;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTamText;
    private javax.swing.JLabel jTlLabel;
    // End of variables declaration//GEN-END:variables
}
