/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankaotomasyonu;

/**
 *
 * @author YILMAZ
 */
public class VadeliFrame extends javax.swing.JFrame {   
        public static User currentUser = null ;

    /**
     * Creates new form VadeliFrame
     */
    public VadeliFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jArkaPanel = new javax.swing.JPanel();
        jCancelLabel = new javax.swing.JLabel();
        jGeriGitLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jVadeliTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jArkaPanel.setBackground(new java.awt.Color(255, 255, 255));

        jCancelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        jCancelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCancelLabelMousePressed(evt);
            }
        });

        jGeriGitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/leftArrow.png"))); // NOI18N
        jGeriGitLabel.setText("GERİ GİT");
        jGeriGitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jGeriGitLabelMousePressed(evt);
            }
        });

        jVadeliTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HESAP NO", "BAKİYE", "VADE SONU BAKİYE", "KALAN GÜN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jVadeliTable.getTableHeader().setReorderingAllowed(false);
        jVadeliTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jVadeliTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jVadeliTable);
        if (jVadeliTable.getColumnModel().getColumnCount() > 0) {
            jVadeliTable.getColumnModel().getColumn(0).setResizable(false);
            jVadeliTable.getColumnModel().getColumn(1).setResizable(false);
            jVadeliTable.getColumnModel().getColumn(2).setResizable(false);
            jVadeliTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yeniHesap.png"))); // NOI18N
        jLabel1.setText("YENİ HESAP OLUSTUR");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ((Musteri)currentUser).hesapFieldAta(2);
        javax.swing.table.DefaultTableModel table = (javax.swing.table.DefaultTableModel)jVadeliTable.getModel();
        if(((Musteri)currentUser).hesapNull(2)){

        }

        else{
            int size = ((Musteri)currentUser).sizeOfHesap(2);
            if(size==0){

            }
            else{
                String[] dataRow = null ; 
                for(int i = 0 ; i < size ; ++i){
                    dataRow = ((Musteri)currentUser).getHesapAtIndex(2,i);
                    table.addRow(dataRow);
                }
            }
        }
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("VADELİ HESAPLARIM");

        javax.swing.GroupLayout jArkaPanelLayout = new javax.swing.GroupLayout(jArkaPanel);
        jArkaPanel.setLayout(jArkaPanelLayout);
        jArkaPanelLayout.setHorizontalGroup(
            jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jArkaPanelLayout.createSequentialGroup()
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jArkaPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jArkaPanelLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel2)))
                .addGap(0, 93, Short.MAX_VALUE))
            .addGroup(jArkaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jArkaPanelLayout.createSequentialGroup()
                        .addComponent(jGeriGitLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jArkaPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCancelLabel)))
                .addContainerGap())
        );
        jArkaPanelLayout.setVerticalGroup(
            jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jArkaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCancelLabel)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGeriGitLabel)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jArkaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jArkaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCancelLabelMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        System.exit(1);
    }//GEN-LAST:event_jCancelLabelMousePressed

    private void jGeriGitLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGeriGitLabelMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        BireyselHesaplarFrame.mainBireyselHesaplarFrame(VadeliFrame.currentUser);
    }//GEN-LAST:event_jGeriGitLabelMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        ((Musteri)currentUser).hesapAta(2);
        VadeliFrame.mainVadeliFrame(currentUser);
        javax.swing.JOptionPane.showMessageDialog(null,"VADELİ HESAP BASVURUNUZ ALINMISTIR\n"
                + "PERSONELLERİMİZ YAKLASIK 5 DAKİKA SONRA HESABINIZI AKTİF YAPACAKTIR!");
    }//GEN-LAST:event_jLabel1MousePressed

    private void jVadeliTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVadeliTableMousePressed
        // TODO add your handling code here:
        int index = jVadeliTable.getSelectedRow();
        if(index!=-1){
           String hesapNo = jVadeliTable.getValueAt(index,0).toString();
           String bakiye = jVadeliTable.getValueAt(index,1).toString();
           String kalanGün = jVadeliTable.getValueAt(index, 2).toString();
           String vadeSonuBakiye = jVadeliTable.getValueAt(index,3).toString();
           if(kalanGün.equals("0")&&vadeSonuBakiye.equals("0")){
               // İLK OLUSTURMA OLDUGU İCİN DİREK BAKİYENİN SECİLECEGİ VADESİZ HESAP SORULMALI YA DA 
               // VADESİZ HESAP YOK İSE ÖNCE VADESİZ HESAP OLUSTURUP ONA PARA YÜKLEYİN DENİLMELİ!
               if(!(((Musteri)currentUser).vadesizHesapVarMi())){
                   this.setVisible(false);
                   this.dispose();
                   VadesizFrame.mainVadesizFrame(currentUser);
                   javax.swing.JOptionPane.showMessageDialog(null,"VADELİ HESABA PARA YATIRMA İSLEMLERİ\nVADESİZ HESAP İLE OLMAKTADIR!\nLUTFEN"
                           + " ONCE VADESİZ HESAP OLUSTURUP BU ISLEMİ OYLE YAPINIZ!");
               }
               else{
                   this.setVisible(false);
                   this.dispose();
                   VadeliIcınVadesizHesap.mainVadeliIcınVadesizFrame(currentUser, hesapNo);
               }
               
           }
           else{
               // ILK OLUSTURULMA DEGIL O ZAMAN FARKLI FRAME ACACAGIZ
               this.setVisible(false);
               this.dispose();
               String[] hesapBilgileri = ((Musteri)currentUser).getHesapAtIndex(2, index);
               VadeliSpesifik.mainVadeliSpesifik(currentUser,hesapBilgileri[0],hesapBilgileri[1],hesapBilgileri[2],hesapBilgileri[3]);
           }
        }
    }//GEN-LAST:event_jVadeliTableMousePressed

    /**
     * @param args the command line arguments
     */
    public static void mainVadeliFrame(User currentUser) {
        VadeliFrame.currentUser = currentUser ; 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VadeliFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VadeliFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VadeliFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VadeliFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VadeliFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jArkaPanel;
    private javax.swing.JLabel jCancelLabel;
    private javax.swing.JLabel jGeriGitLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jVadeliTable;
    // End of variables declaration//GEN-END:variables
}
