/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankaotomasyonu;

/**
 *
 * @author YILMAZ
 */
public class YatirimIcinBakiye extends javax.swing.JFrame {
    public static User currentUser = null ; 
    public static String yatirimHesapNo ; 
    public static VadesizHesap vadesizHesap ; 
    public static int flag ; 
    public static double gramAltinFiyat ; 
    public static double dolarFiyat;
    public static double euroFiyat;
    /**
     * Creates new form YatirimIcinBakiye
     */
    public YatirimIcinBakiye() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jArkaPanel = new javax.swing.JPanel();
        jCancelLabel = new javax.swing.JLabel();
        jGeriLabel = new javax.swing.JLabel();
        jYaziLabel = new javax.swing.JLabel();
        jTamText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jNoktaLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jOndalikText = new javax.swing.JTextField();
        jResimLabel = new javax.swing.JLabel();
        jOutputText = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jDevamLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jArkaPanel.setBackground(new java.awt.Color(255, 255, 255));

        jCancelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        jCancelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCancelLabelMousePressed(evt);
            }
        });

        jGeriLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/leftArrow.png"))); // NOI18N
        jGeriLabel.setText("GERİ GİT");
        jGeriLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jGeriLabelMousePressed(evt);
            }
        });

        jYaziLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jYaziLabel.setText("BAKİYE GİRİNİZ");

        jTamText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTamText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTamText.setBorder(null);
        jTamText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTamTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTamTextKeyReleased(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jNoktaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jNoktaLabel.setText(".");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jOndalikText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jOndalikText.setBorder(null);
        jOndalikText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jOndalikTextKeyReleased(evt);
            }
        });

        jResimLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gold.png"))); // NOI18N

        jOutputText.setEditable(false);
        jOutputText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jOutputText.setBorder(null);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jDevamLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/devam.png"))); // NOI18N
        jDevamLabel.setText("ONAYLA");
        jDevamLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        if(flag==1){

        }
        else if(flag==2){
            jResimLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dolar.png"))); // NOI18N
        }
        else { // flag == 3
            jResimLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/euro.png"))); // NOI18N
        }
        jDevamLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jDevamLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jArkaPanelLayout = new javax.swing.GroupLayout(jArkaPanel);
        jArkaPanel.setLayout(jArkaPanelLayout);
        jArkaPanelLayout.setHorizontalGroup(
            jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jArkaPanelLayout.createSequentialGroup()
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jArkaPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCancelLabel))
                    .addGroup(jArkaPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jTamText, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jNoktaLabel)
                        .addGap(18, 18, 18)
                        .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(jOndalikText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jArkaPanelLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jYaziLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(jResimLabel)
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jArkaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jOutputText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
            .addGroup(jArkaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jGeriLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDevamLabel)
                .addContainerGap())
        );
        jArkaPanelLayout.setVerticalGroup(
            jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jArkaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCancelLabel)
                .addGap(70, 70, 70)
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jArkaPanelLayout.createSequentialGroup()
                        .addComponent(jYaziLabel)
                        .addGap(86, 86, 86)
                        .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTamText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNoktaLabel)
                            .addComponent(jOndalikText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jOutputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jResimLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jArkaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGeriLabel)
                    .addComponent(jDevamLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jArkaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jArkaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCancelLabelMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        System.exit(1);
    }//GEN-LAST:event_jCancelLabelMousePressed

    private void jGeriLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGeriLabelMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        YatirimIcınVadesizHesap.mainYatırımIcınVadesizHesap(currentUser, yatirimHesapNo, flag);
    }//GEN-LAST:event_jGeriLabelMousePressed

    private void jTamTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTamTextKeyReleased
        // TODO add your handling code here:
        long tam,ondalik;
        double kullaniciSayisi ; // Kullanıcın istedgi tutar ama vadesiz hesabından daha fazla girmis ise bunu kontol etmem lazım!
        double vadesizSayi ;
        try{
            if(jTamText.getText().equals(""));
            else  Long.valueOf(jTamText.getText());

            if(jOndalikText.getText().equals("")) ;
            else  Long.valueOf(jOndalikText.getText());
            // SİMDİYE KADAR NUMBER FORMATINDA SIKINTI VARSA DİYE YAPTIK EGER BURAYI GECER ISE SAYI FORMATINDA SIKINTI YOKTUR!
            if(jTamText.getText().equals("")) tam = 0 ;
            else tam = Long.valueOf(jTamText.getText());
            //----------------------------
            vadesizSayi = Double.valueOf(vadesizHesap.getBakiye());
            if((long)vadesizSayi < tam){
                jTamText.setText(String.valueOf((long)vadesizSayi));
            }
            else{

            }
            if(jOndalikText.getText().equals("")) ondalik = 0 ; 
            else ondalik = Long.valueOf(jOndalikText.getText());
            kullaniciSayisi = Double.valueOf(String.valueOf(tam)+"."+String.valueOf(ondalik));
            if(flag == 1){
                double gramAltin = kullaniciSayisi/gramAltinFiyat;
                gramAltin = (double)Math.round(gramAltin*100)/100;
                jOutputText.setText(String.valueOf(gramAltin)+" gram ");
            }
            else if(flag == 2){
                double dolar = kullaniciSayisi/dolarFiyat;
                dolar = (double)Math.round(dolar*100)/100;
                jOutputText.setText(String.valueOf(dolar)+" dolar");
            }
            else { // flag == 3
                double euro = kullaniciSayisi/euroFiyat;
                euro = (double)Math.round(euro*100)/100;
                jOutputText.setText(String.valueOf(euro)+" euro");
            }            
            
        }catch(NumberFormatException e ){
            jTamText.setText("");
            jOutputText.setText("");
        }

    }//GEN-LAST:event_jTamTextKeyReleased

    private void jOndalikTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jOndalikTextKeyReleased
        // TODO add your handling code here:
        long tam, ondalik;
        double kullaniciSayisi;
        double vadesizSayi;
        try{
            if(jTamText.getText().equals(""));
            else  Long.valueOf(jTamText.getText());

            if(jOndalikText.getText().equals("")) ;
            else  Long.valueOf(jOndalikText.getText());
            // SİMDİYE KADAR NUMBER FORMATINDA SIKINTI VARSA DİYE YAPTIK EGER BURAYI GECER ISE SAYI FORMATINDA SIKINTI YOKTUR!
            if(jTamText.getText().equals("")&&jOndalikText.getText().equals("")){
                kullaniciSayisi = 0.0 ;
            }
            else if(jTamText.getText().equals("")||jOndalikText.getText().equals("")){
                if(jTamText.getText().equals("")){
                    kullaniciSayisi = Double.valueOf("0."+jOndalikText.getText());
                }
                else{
                    kullaniciSayisi = Double.valueOf(jTamText.getText()+".0");
                }
            }
            else{
                kullaniciSayisi = Double.valueOf(jTamText.getText()+"."+jOndalikText.getText());
            }
            vadesizSayi = Double.valueOf(vadesizHesap.getBakiye());
            if(vadesizSayi < kullaniciSayisi){
                java.util.StringTokenizer token = new java.util.StringTokenizer(vadesizHesap.getBakiye(),".");
                jTamText.setText(token.nextToken());
                jOndalikText.setText(token.nextToken());
            }
            else{

            }
            if(flag == 1){
                double gramAltin = kullaniciSayisi/gramAltinFiyat;
                gramAltin = (double)Math.round(gramAltin*100)/100;
                jOutputText.setText(String.valueOf(gramAltin)+" gram ");
            }
            else if(flag == 2){
                double dolar = kullaniciSayisi/dolarFiyat;
                dolar = (double)Math.round(dolar*100)/100;
                jOutputText.setText(String.valueOf(dolar)+" dolar");
            }
            else { // flag == 3
                double euro = kullaniciSayisi/euroFiyat;
                euro = (double)Math.round(euro*100)/100;
                jOutputText.setText(String.valueOf(euro)+" euro");
            }

        }catch(NumberFormatException e){
            jOndalikText.setText("");
            jOutputText.setText("");
        }catch(NullPointerException e1){
            javax.swing.JOptionPane.showMessageDialog(null,"BİLGİNİN SAKNLAMASINDA HATA VAR!");
        }
    }//GEN-LAST:event_jOndalikTextKeyReleased

    private void jDevamLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDevamLabelMousePressed
        // TODO add your handling code here:
        String tam = jTamText.getText();
        String ondalik = jOndalikText.getText();
        if(tam == null || tam.equals("")){
            tam = "0";
        }
        if(ondalik == null || ondalik.equals("")){
            ondalik ="0";
        }
        String para = tam+"."+ondalik;
        
        try{
        double vadeliHesapPara = Double.valueOf(para);
        if(vadeliHesapPara <=0){
            javax.swing.JOptionPane.showMessageDialog(null,"YUKLEMEK ISTEDIGINIZ BAKİYE NEGATİF VEYA SIFIR OLAMAZ");
            this.setVisible(false);
            this.dispose();
            YatirimIcınVadesizHesap.mainYatırımIcınVadesizHesap(currentUser, yatirimHesapNo,flag);
            return ; 
        }
        else{
            if(!((((Musteri)currentUser).vadesizHesapBakiye(vadesizHesap.getHesapNo(), vadeliHesapPara, false)))){
                // yani cikarma islemi bakiye yetersizliginden olmamis ise
                this.setVisible(false);
                this.dispose();
                VadeliFrame.mainVadeliFrame(currentUser);
                javax.swing.JOptionPane.showMessageDialog(null,"SECİLEN VADESİZ HESAPTA BU KADAR PARA YOK!");
            }
            else{
                this.setVisible(false);
                this.dispose();
                java.util.StringTokenizer token = new java.util.StringTokenizer(jOutputText.getText());
                double b_d_e = Double.valueOf(token.nextToken());
                ((Musteri)currentUser).yatirimHesapInit(yatirimHesapNo,vadeliHesapPara , b_d_e , flag);
                YatirimFrame.mainYatirimFrame(currentUser);
            }
        }
        
        }catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null,"LUTFEN SADECE RAKAM GİRİNİZ!");
        }
    }//GEN-LAST:event_jDevamLabelMousePressed

    private void jTamTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTamTextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTamTextKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void mainYatirimIcinBakiye(User currentUser, String yatirimHesapNo,VadesizHesap vadesizHesap,int flag) {
        YatirimIcinBakiye.currentUser = currentUser;
        YatirimIcinBakiye.yatirimHesapNo = yatirimHesapNo;
        YatirimIcinBakiye.vadesizHesap = vadesizHesap;
        YatirimIcinBakiye.flag = flag ; 
        if(flag== 1){
            gramAltinFiyat = YatirimHesabi.fiyatVer(flag);
        }
        else if(flag==2){
            dolarFiyat = YatirimHesabi.fiyatVer(flag);
        }
        else if(flag==3){
            euroFiyat = YatirimHesabi.fiyatVer(flag);
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YatirimIcinBakiye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YatirimIcinBakiye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YatirimIcinBakiye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YatirimIcinBakiye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YatirimIcinBakiye().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jArkaPanel;
    private javax.swing.JLabel jCancelLabel;
    private javax.swing.JLabel jDevamLabel;
    private javax.swing.JLabel jGeriLabel;
    private javax.swing.JLabel jNoktaLabel;
    private javax.swing.JTextField jOndalikText;
    private javax.swing.JTextField jOutputText;
    private javax.swing.JLabel jResimLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTamText;
    private javax.swing.JLabel jYaziLabel;
    // End of variables declaration//GEN-END:variables
}
